[package]
name = "ili9225"
version = "0.1.0"
authors = ["413<the413reply@gmail.com>"]
edition = "2021"
repository = "https://github.com/syx-413/ILI9225"
keywords = ["ili9225", "display", "embedded"]
readme = "README.md"

[dependencies]
